spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=login_conagua;encrypt=true;trustServerCertificate=true
    username: SA
    password: W8-4ARMTCX
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
